sudo: false
dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -U pipenv==2018.11.26 codecov
  - pipenv install --dev --deploy
script:
  - make
  - pytest --cov txmaker
after_success:
  - codecov
